[component]
structures = [ "content_blocks" ]
label = "Hero"
description = "Page hero with the heading, description, buttons, and an image"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "Hi there!"
description_html = "<strong>Data Science Enthusiast</strong> and <strong>Programming Lover</strong>. I share my learnings in short YouTube videos, covering various topics like Explainable AI,  Graph Neural Networks, Generative Deep Learning, ML Ops, Computer Vision or Uncertainty Estimation."
image = "/images/deepfindr_logo.png"
image_alt = "DeepFindr logo"
cta_button = "Get in touch"
cta_button_link = "#contact"
works_button = "See my videos"
works_button_link = "#videos"