[component]
structures = [ "content_blocks" ]
label = "Videos"
description = "Videos Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Latest Videos"
description_html = "Great things are not done by impulse, but by a series of small things brought together. <br> - <i> Vincent Van Gogh </i>"
link_url = "/videos"
show_videos = true